server:
  port: 9002
  tomcat:
    max-threads: 10
    
spring:
  application:
    name: service-order #服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册