server:
  port: 9004
spring:
  application:
    name: service-order
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 #配置sentinel控制台请求路径
      datasource:
        ds1:
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: flow
      eager: true #立即加载sentinel控制台数据
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true

#配置feign日志的输出
#日志配置  NONE : 不输出日志(高)   BASIC: 适用于生产环境追踪问题
#HEADERS : 在BASIC的基础上,记录请求和响应头信息   FULL : 记录所有
feign:
  client:
    config:
      service-product:  #需要调用的服务名称
        loggerLevel: FULL

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: ExecutionIsolationStrategy.SEMAPHORE #信号量隔离 #ExecutionIsolationStrategy.THREAD #线程池隔离
          maxConcurrentRequests: 50 #最大信号量上限
          thread:
            timeoutInMilliseconds: 3000 #默认连接超时时间为1S，若超过1S,自动触发熔断降级
      circuitBreaker:
        requestVolumeThreshold: 20 #触发熔断的最小请求次数
        sleepWindowInMillseconds: 1000 #触发熔断之后 多久之后再开始尝试请求
        errorThresholdPercentage: 50 #触发熔断器的失败请求最小占比，默认50