server:
  port: 9003
spring:
  application:
    name: service-order-frign
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 #配置sentinel控制台请求路径
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    
#配置feign日志的输出
#日志配置  NONE : 不输出日志(高)   BASIC: 适用于生产环境追踪问题
#HEADERS : 在BASIC的基础上,记录请求和响应头信息   FULL : 记录所有
feign:
  client:
    config:
      service-product:  #需要调用的服务名称
        loggerLevel: FULL
  sentinel:
    enabled: true
    
  #开启对hystrix的支持
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'