server:
  port: 7001 #端口
spring:
  application:
    name: rabbit-consumer #服务名称
  rabbitmq:
    addresses: 192.168.0.1 #请求路径
    username: guest
    password: guest
  cloud:
    stream:
      instance-count: 2 #消费者总数
      instance-index: 0 #当前消费者索引
      bindings:
        my_input:
          destination: idealismus-custom
          group: group1 #设置消费组的名称（同名组中多个消费者，只有一个去消费）
          consumer:
            partitioned: true #开启分区支持      
        input: #管道 获取消息的通道
          destination: idealismus #指定消息的获取exchange
      binders: #配置绑定器
        defaultRabbit:
          type: rabbit