server:
  port: 8080
spring:
  application:
    name: api-gateway-server
#配置SpringCloudGateway的路由
  cloud:
    gateway:
      routes: 
        #配置路由，路由ID，路由到微服务的uri。断言（判断条件
       - id: product-service #id唯一
         #uri: http://127.0.0.1:9001 #目标微服务地址
         uri: lb://service-product #lb:// 代表根据微服务名称从注册中心拉取服务请求路径
         predicates: 
           #- Path=/product/** #path，路径
           - Path=/product-service/**
         filters:
           - RewritePath=/product-service/(?<segment>.*), /$\{segment}
      #配置自动根据微服务名称进行路由转发
      discovery:
        locator:
          enabled: true #开启根据服务名称自动转发
          lower-case-service-id: true #微服务名称以小写形式呈现
#eurka注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true