server:
  port: 53020
  use-forward-headers: true
  servlet:
    context-path: /uaa

spring:
  application:
    name: uaa
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  freemarker:
    enabled: true
    content-type: text/html
    suffix: .html
    request-context-attribute: rc
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
      
logging:
  level:
    root: info
    org.springframework.web: info
management:
  endpoints:
    web:
      exposure:
        include: refresh,healeth,info,env
eureka:
  client:
    service-url:
      defaultZone: http://localhost:53000/eureka/
  instance:
    prefer-ip-address: true
    instance_id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
mybatis-plus:
  #实体类扫描路径
  type-aliases-package: ink.taofu.security.entity
  #xml文件扫描路径
  mapper-locations: classpath:mapper/*.xml

  #全局设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      filed-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
    confiuration:
      #是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
      map-underscore-to-camel-case: true
      #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
      call-setters-on-nulls: true
      #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl