server:
  port: 9001
spring:
  application:
    name: service-product
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: TIANZHIDAO233
    
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  zipkin:
    base-url: http://localhost:9411/ #server请求地址
    sender:
      type: web #数据传输方式。http形式向server端发送
    sleuth:
      sampler:
        probability: 1 #采样比
#配置eurekaClient  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
      #同时向多个eureka主机注册
      #defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
  instance:
    #使用IP地址注册
    prefer-ip-address: true
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug