server:
  port: 56082
swagger:
  enable: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer_bank2
    
logging:
  level:
    root: info
    org.springframework.web: info
    cn.idealismus: debug