server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: security
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.145.233:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: TIANZHIDAO@233
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
#设置mybatis Mapper的扫描路径
mybatis-plus:
  #实体类扫描路径
  type-aliases-package: ink.taofu.security.entity
  #xml文件扫描路径
  mapper-locations: classpath:mapper/*.xml

  #全局设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      filed-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
    confiuration:
      #是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
      map-underscore-to-camel-case: true
      #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
      call-setters-on-nulls: true
      #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl