server:
  port: 10000
spring:
  application:
    name: config-server #服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/heureka/config-repo.git
  rabbitmq:
    host: 124.156.103.105
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoint:
    web:
      exposure:
        include: bus-refresh