server:
  port: 53021
  use-forward-headers: true
  servlet:
    context-path: /order

spring:
  application:
    name: order
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  freemarker:
    enabled: true
    content-type: text/html
    suffix: .html
    request-context-attribute: rc
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
logging:
  level:
    root: info
    org.springframework.web: info
management:
  endpoints:
    web:
      exposure:
        include: refresh,healeth,info,env
eureka:
  client:
    service-url:
      defaultZone: http://localhost:53000/eureka/
  instance:
    prefer-ip-address: true
    instance_id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}