server:
  port: 8031
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
turbine:
  #需要监控的微服务列表，多个用 ',' 分隔
  app-config: service-order
  cluster-name-expression: "'default'"
